default_platform(:ios)
platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if is_ci
    xcode_select("/Applications/Xcode_15.0.app") if is_ci
    match(type: "development", readonly: is_ci)
    match(type: "appstore", readonly: is_ci)
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY"],
      is_key_content_base64: true,
      in_house: false,
    )
    increment_build_number({
      build_number: latest_testflight_build_number(
        version: get_version_number(
          target: "TypstApp",
        ),
        app_identifier: "dev.tiankaima.TypstApp",
      ) + 1,
    })
    build_app(scheme: "TypstApp")
    pilot(skip_waiting_for_build_processing: true)
  end
end
